# Permalinks
permalink:           pretty
# permalink: /words/:title.html

# Setup
title:               Philippe Dionne
tagline:             # The Jekyll Butler
description: > # this means to ignore newlines until "baseurl:"
  I’m Philippe Dionne, a 28 years old french Canadian with a passion for æsthetics & technology striving for a higher purpose. I work in Quebec city and chase my dreams everyday.
url:                 http://phildionne.com
baseurl:             ""
analytics_id:        "UA-11657486-3"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          /
  style:            :compressed
exclude:
  - ".env"

# Build settings
markdown: kramdown

  # About/contact
author:
  name:              Philippe Dionne
  url:               https://twitter.com/phildionne
  email:             dionne.phil@gmail.com

# Gems
gems:
  - jekyll-gist
