# Permalinks
permalink: /words/:title.html

# Setup
title: Philippe Dionne
description: >-
  I’m Philippe Dionne, a french Canadian with a passion for æsthetics & technology striving for a higher purpose. I work in Quebec city and chase my dreams everyday.
baseurl: ""
url: https://phildionne.com
analytics_id: "UA-11657486-3"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass

# Build settings
markdown: kramdown

  # About/contact
author:
  name: Philippe Dionne
  url: https://twitter.com/phildionne
  email: dionne.phil@gmail.com

# Exclusions
exclude:
  - .env
