backend:
  name: github
  repo: phildionne/phildionne.com # Path to your Github repository
  branch: master # Branch to update
  site_domain: phildionne.com # Your Netlify site address if different from host

media_folder: "assets/uploads"

collections:
  - name: "words"
  - label: "Words"
  - folder: "words/_posts"
  - create: true
  - slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  - fields:
    - { label: "Layout", name:"layout", widget: "string" }
    - { label: "Active", name:"active", widget: "string" }
    - { label: "Title", name:"title", widget: "string" }
    - { label: "Year", name:"year", widget: "number" }
    - { label: "Categories", name:"categories", widget: "string" }
    - { label: "Footer", name:"footer", widget: "string" }
    - { label: "Body Id", name:"body_id", widget: "string" }
    - { label: "Locale", name:"locale", widget: "string" }
    - { label: "Body", name:"body", widget: "markdown" }
